"""create templates table

Revision ID: 0cb1b0460bb8
Revises: bd556637689d
Create Date: 2026-02-08 16:00:22.368300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb1b0460bb8'
down_revision = 'bd556637689d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), server_default='both', nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_templates_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_type'))
        batch_op.drop_index(batch_op.f('ix_templates_name'))
        batch_op.drop_index(batch_op.f('ix_templates_created_by_id'))

    op.drop_table('templates')
    # ### end Alembic commands ###
