"""update role column in users

Revision ID: 700e12bd3c89
Revises: 6b1b5925e5b4
Create Date: 2026-02-08 15:24:11.264639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700e12bd3c89'
down_revision = '6b1b5925e5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    # ### end Alembic commands ###
